<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputPath>../../obj/verify-hex/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\KoboldCom\HexProtocolAnalyzer.cs" />
    <Compile Include="..\..\KoboldCom\ProtocolAnalyzer.cs" />
    <Compile Include="..\..\KoboldCom\CheckSumHandler.cs" />
    <Compile Include="..\..\KoboldCom\SearchResult.cs" />
    <Compile Include="..\..\KoboldCom\IAnalyzer.cs" />
  </ItemGroup>
</Project>
