<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>KoboldCom</RootNamespace>
    <AssemblyName>KoboldCom</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Version>2.0.0</Version>
    <PackageVersion>2.0.0</PackageVersion>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <InformationalVersion>2.0.0</InformationalVersion>
    <AssemblyTitle>KoboldCom</AssemblyTitle>
    <Description>Serial Port Communication Tool</Description>
    <Product>KoboldCom</Product>
    <Copyright>Copyright © Shizhy  2014</Copyright>
    <Company></Company>
    <NeutralLanguage>zh-Hans</NeutralLanguage>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="KoboldCom.ico" />
  </ItemGroup>
</Project>
